apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  workspaces:
  - name: workspace
  tasks:
    - name: git-clone
      params:
       - name: url
         value: "https://github.com/enzokamal/nodeapp.git"
       - name: revision
         value: "main"
      workspaces:
      - name: workspace
        workspace: workspace
      taskRef:
        name: git-clone
    - name: build-push
      taskRef:
        name: build-push
      params:
        - name: dockerignore
          value: ".git"
      runAfter:
        - git-clone
      workspaces:
        - name: workspace
          workspace: workspace
    - name: deploy
      workspaces:
      - name: workspace
        workspace: workspace
      taskRef:
        name: deploy
      runAfter: 
        - build-push